name: rule_based_chatbot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  url_launcher: ^6.3.2
  provider: ^6.1.5+1
  lottie: ^3.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/chatbot.png"

flutter:
  uses-material-design: true
  assets:
    - assets/chatbotnew.json
    - assets/images/chatbot.png
